In [ ]:
# Loading ecommerce_dataset

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
sales_data = pd.read_csv('ecommerce_sales.csv')
sales_data.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56

## 1.CLEANING SALES DATA

### Numbers of rows and column in dataset

In [6]:
sales_data.shape

(5000, 12)

#### what are the columns or fields provided in the dataset?

In [7]:
sales_data.columns

Index(['order_id', 'order_date', 'customer_id', 'product_category', 'region',
       'quantity', 'unit_price', 'discount', 'payment_method', 'delivery_days',
       'customer_rating', 'revenue'],
      dtype='object')

#### Information about the sales data

In [8]:
sales_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   object
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   object
 4   region            5000 non-null   object
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   object
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: float64(4), int64(4), object(4)
memory usage: 468.9+ KB

#### General statistics

In [12]:
sales_data.describe()

,order_id,customer_id,quantity,unit_price,discount,delivery_days,customer_rating,revenue
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,12500.500000,1505.701200,4.044800,308.418774,0.179984,6.118800,2.973980,1021.955148
std,1443.520003,290.836902,2.020398,169.259369,0.101404,3.153264,1.157722,825.584219
min,10001.000000,1000.000000,1.000000,15.150000,0.000000,1.000000,1.000000,11.210000
25%,11250.750000,1253.000000,2.000000,161.895000,0.090000,3.000000,2.000000,354.527500
50%,12500.500000,1510.000000,4.000000,309.890000,0.180000,6.000000,3.000000,796.650000
75%,13750.250000,1761.000000,6.000000,455.557500,0.270000,9.000000,4.000000,1515.690000
max,15000.000000,1999.000000,7.000000,599.960000,0.350000,11.000000,5.000000,4119.330000

### Checking if the data contains duplicate values

In [23]:
sales_data.duplicated().sum()

np.int64(0)

In [22]:
sales_data.loc[sales_data.duplicated()]

Empty DataFrame
Columns: [order_id, order_date, customer_id, product_category, region, quantity, unit_price, discount, payment_method, delivery_days, customer_rating, revenue]
Index: []

##### There are no duplicate data in the dataset.

### Check if the data consists of any null value

In [25]:
sales_data.isnull().sum()

order_id            0
order_date          0
customer_id         0
product_category    0
region              0
quantity            0
unit_price          0
discount            0
payment_method      0
delivery_days       0
customer_rating     0
revenue             0
dtype: int64

#### There are no null values in the dataset

In [26]:
sales_data.isna().sum()

order_id            0
order_date          0
customer_id         0
product_category    0
region              0
quantity            0
unit_price          0
discount            0
payment_method      0
delivery_days       0
customer_rating     0
revenue             0
dtype: int64

In [ ]:
# There are no missing values in the dataset

In [27]:
sales_data.head()

,order_id,order_date,customer_id,product_category,region,quantity,unit_price,discount,payment_method,delivery_days,customer_rating,revenue
0,10001,1/1/2022,1102,Beauty,South,7,373.65,0.28,Wallet,10,4.7,1883.20
1,10002,1/2/2022,1435,Clothing,South,7,47.74,0.09,Card,6,3.9,304.10
2,10003,1/3/2022,1860,Beauty,East,3,311.28,0.31,COD,6,2.5,644.35
3,10004,1/4/2022,1270,Electronics,West,5,524.47,0.02,Wallet,6,1.6,2569.90
4,10005,1/5/2022,1106,Clothing,West,5,139.87,0.33,Wallet,4,4.9,468.56

### Dealing with the order_date (converting datatype)

In [34]:
sales_data.order_date.dtype

dtype('O')

In [35]:
sales_data.order_date = pd.to_datetime(sales_data.order_date )

### converted the datatype of date from object to datetime

In [36]:
sales_data.order_date.dtype

dtype('<M8[ns]')

In [39]:
sales_data.order_date.head()

0   2022-01-01
1   2022-01-02
2   2022-01-03
3   2022-01-04
4   2022-01-05
Name: order_date, dtype: datetime64[ns]

In [52]:
# sales_data.loc[sales_data['quantity']<0]
#sales_data.loc[sales_data['unit_price']<0]
#sales_data.loc[sales_data['customer_rating']<0]
#sales_data.loc[sales_data['revenue']<0]
#sales_data.loc[(sales_data['discount']<0) | (sales_data['discount']>1 ) ]

Empty DataFrame
Columns: [order_id, order_date, customer_id, product_category, region, quantity, unit_price, discount, payment_method, delivery_days, customer_rating, revenue]
Index: []

In [53]:
pwd

'C:\\Users\\Dell\\projects\\ecommerce_sales_analysis'

In [83]:
%cd "C:\\Users\\Dell\\projects"

C:\Users\Dell\projects

In [84]:
ls

 Volume in drive C is OS
 Volume Serial Number is 02CA-6946

 Directory of C:\Users\Dell\projects

09/15/2026  08:22 PM    <DIR>          .
09/04/2026  09:23 PM    <DIR>          ..
08/18/2026  06:18 PM    <DIR>          .ipynb_checkpoints
09/15/2026  09:14 PM    <DIR>          ecommerce_sales_analysis
09/04/2026  03:18 PM    <DIR>          netflix_data_analysis
               0 File(s)              0 bytes
               5 Dir(s)  324,712,529,920 bytes free

In [85]:
!git add ecommerce_sales_analysis

warning: in the working copy of 'ecommerce_sales_analysis/.ipynb_checkpoints/ecommerce_sales_anlaysis-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'ecommerce_sales_analysis/ecommerce_sales_anlaysis.ipynb', LF will be replaced by CRLF the next time Git touches it

In [ ]:
!git commit -m "Ecommerce sales analysisi"